# SUMMARY = "Custom config file for dnsmasq"
# DESCRIPTION = "This config file provides access limits and dhcp for wi-fi in access point mode"

# Limit DHCP a wlan0
interface=wlan0

# Limit access point DHCP range (2-20)
dhcp-range=192.168.1.2,192.168.1.20,255.255.255.0,24h